development:
  host: localhost
  database: mongoblog_development

test:
  host: localhost
  database: mongoblog_test

# set these environment variables on your prod server
#Commented by aditya

#production:
 # host: <%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  #database: <%= ENV['MONGOID_DATABASE'] %>
  # Till here

  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
production:
  sessions:
    default:
      uri: "mongodb://Aditya Srivastava:aditya0007@kahana.mongohq.com:10087/mongoDB"
      options:
        safe: true
        skip_version_check: true